import {
  Organization,
  Customer,
  Supplier,
  Product,
  Transaction,
  Expense,
  Invoice,
  BusinessDocument,
  Task,
  Insight,
  ExecutiveReport,
  OrganizationMember
} from '../types';

export const DEMO_ORG_ID = 'org_acme_nigeria_001';

export const demoOrganization: Organization = {
  id: DEMO_ORG_ID,
  name: 'Acme Distribution Nigeria',
  tagline: 'Leading Fast-Moving Consumer Goods (FMCG) Wholesale & Logistics across Nigeria',
  currency: 'NGN',
  currencySymbol: '₦',
  country: 'Nigeria',
  industry: 'FMCG & Wholesale Distribution',
  taxId: 'TIN-23490184-0001',
  address: 'Plot 14, Commercial Avenue, Ikeja Industrial Estate, Lagos, Nigeria',
  phone: '+234 1 295 4400',
  email: 'operations@acmedistribution.ng',
  ownerId: 'user_demo_owner',
  createdAt: '2025-01-15T08:00:00.000Z',
};

export const demoMembers: OrganizationMember[] = [
  {
    id: 'mem_1',
    organizationId: DEMO_ORG_ID,
    userId: 'user_demo_owner',
    email: 'efeisiavwe@gmail.com',
    displayName: 'Efe Isiavwe',
    role: 'Owner',
    joinedAt: '2025-01-15T08:00:00.000Z',
  },
  {
    id: 'mem_2',
    organizationId: DEMO_ORG_ID,
    userId: 'user_demo_admin',
    email: 'adebayo.o@acmedistribution.ng',
    displayName: 'Adebayo Ogunlesi',
    role: 'Admin',
    joinedAt: '2025-01-20T09:30:00.000Z',
  },
  {
    id: 'mem_3',
    organizationId: DEMO_ORG_ID,
    userId: 'user_demo_manager',
    email: 'ngozi.e@acmedistribution.ng',
    displayName: 'Ngozi Ezeh',
    role: 'Manager',
    joinedAt: '2025-02-01T10:00:00.000Z',
  },
  {
    id: 'mem_4',
    organizationId: DEMO_ORG_ID,
    userId: 'user_demo_analyst',
    email: 'tunde.b@acmedistribution.ng',
    displayName: 'Babatunde Alabi',
    role: 'Analyst',
    joinedAt: '2025-02-15T11:15:00.000Z',
  },
  {
    id: 'mem_5',
    organizationId: DEMO_ORG_ID,
    userId: 'user_demo_staff',
    email: 'khalid.m@acmedistribution.ng',
    displayName: 'Khalid Mohammed',
    role: 'Staff',
    joinedAt: '2025-03-01T08:45:00.000Z',
  }
];

export const demoCustomers: Customer[] = [
  {
    id: 'cust_01',
    organizationId: DEMO_ORG_ID,
    name: 'Danladi Supermarkets Ltd',
    contactPerson: 'Alhaji Danladi Usman',
    email: 'danladi.stores@yahoo.com',
    phone: '+234 803 456 7890',
    address: 'Garki Commercial District II',
    city: 'Abuja, FCT',
    totalPurchases: 48500000,
    outstandingBalance: 6850000,
    paymentTerms: 'Net 30',
    creditLimit: 10000000,
    paymentHealth: 'Overdue',
    lastOrderDate: '2026-08-14',
    notes: 'Outstanding on Inv #INV-2026-088. Overdue by 28 days. Follow up with Alhaji Danladi.',
    createdAt: '2025-02-01T10:00:00.000Z',
  },
  {
    id: 'cust_02',
    organizationId: DEMO_ORG_ID,
    name: 'Eze & Sons Trading Enterprises',
    contactPerson: 'Chief Jude Eze',
    email: 'jude.eze@ezesons.com.ng',
    phone: '+234 802 334 5566',
    address: 'Main Market Zone 4',
    city: 'Onitsha, Anambra',
    totalPurchases: 62000000,
    outstandingBalance: 9200000,
    paymentTerms: 'Net 30',
    creditLimit: 12000000,
    paymentHealth: 'Slow',
    lastOrderDate: '2026-08-20',
    notes: 'High volume wholesale buyer. Always settles within 45 days, partial payment expected this Friday.',
    createdAt: '2025-01-20T10:00:00.000Z',
  },
  {
    id: 'cust_03',
    organizationId: DEMO_ORG_ID,
    name: 'Lekki Palm Grocers & Bakery',
    contactPerson: 'Mrs. Folake Badmus',
    email: 'purchases@lekkipalm.com',
    phone: '+234 809 112 2334',
    address: 'Admiralty Way, Lekki Phase 1',
    city: 'Lagos',
    totalPurchases: 31400000,
    outstandingBalance: 0,
    paymentTerms: 'Net 15',
    creditLimit: 5000000,
    paymentHealth: 'Good',
    lastOrderDate: '2026-08-28',
    notes: 'Punctual payer with pristine payment history. Eligible for bulk tier discount.',
    createdAt: '2025-02-10T10:00:00.000Z',
  },
  {
    id: 'cust_04',
    organizationId: DEMO_ORG_ID,
    name: 'Kano Mega Stores & Provisioners',
    contactPerson: 'Mallam Sani Garba',
    email: 'sani.garba@kanomega.ng',
    phone: '+234 805 778 9900',
    address: 'Bompai Industrial Area',
    city: 'Kano',
    totalPurchases: 39800000,
    outstandingBalance: 4100000,
    paymentTerms: 'Net 30',
    creditLimit: 8000000,
    paymentHealth: 'Slow',
    lastOrderDate: '2026-08-10',
    notes: 'Requested delay due to interstate freight inspection at Lokoja.',
    createdAt: '2025-03-05T10:00:00.000Z',
  },
  {
    id: 'cust_05',
    organizationId: DEMO_ORG_ID,
    name: 'Bodija Wholesale Mart',
    contactPerson: 'Elder Segun Adeleke',
    email: 'bodija.mart@gmail.com',
    phone: '+234 814 667 8899',
    address: 'Bodija Market Road',
    city: 'Ibadan, Oyo',
    totalPurchases: 27500000,
    outstandingBalance: 1450000,
    paymentTerms: 'Net 15',
    creditLimit: 4000000,
    paymentHealth: 'Good',
    lastOrderDate: '2026-08-25',
    notes: 'Consistent weekly purchaser of Golden Penny Flour and Sugar.',
    createdAt: '2025-03-20T10:00:00.000Z',
  },
  {
    id: 'cust_06',
    organizationId: DEMO_ORG_ID,
    name: 'Garden City Retailers Consortium',
    contactPerson: 'Dr. Tonye Briggs',
    email: 't.briggs@gardencityretail.com',
    phone: '+234 803 999 1122',
    address: 'Trans-Amadi Industrial Layout',
    city: 'Port Harcourt, Rivers',
    totalPurchases: 18200000,
    outstandingBalance: 3200000,
    paymentTerms: 'Net 30',
    creditLimit: 6000000,
    paymentHealth: 'At Risk',
    lastOrderDate: '2026-07-28',
    notes: 'Payment overdue by 34 days. Credit limit temporarily frozen.',
    createdAt: '2025-04-01T10:00:00.000Z',
  }
];

export const demoSuppliers: Supplier[] = [
  {
    id: 'supp_01',
    organizationId: DEMO_ORG_ID,
    name: 'Dangote Sugar Refinery Plc',
    contactPerson: 'Ibrahim Bello',
    email: 'sales@dangotesugar.com.ng',
    phone: '+234 1 271 2222',
    category: 'Sugar & Commodities',
    totalPurchases: 84000000,
    balanceDue: 5500000,
    rating: 4.8,
  },
  {
    id: 'supp_02',
    organizationId: DEMO_ORG_ID,
    name: 'Flour Mills of Nigeria Plc (Golden Penny)',
    contactPerson: 'Chinedu Okonkwo',
    email: 'orders@fmnplc.com',
    phone: '+234 1 280 1000',
    category: 'Flour & Grains',
    totalPurchases: 95000000,
    balanceDue: 0,
    rating: 4.9,
  },
  {
    id: 'supp_03',
    organizationId: DEMO_ORG_ID,
    name: 'Dufil Prima Foods Plc (Indomie)',
    contactPerson: 'Deepak Sharma',
    email: 'distribution@dufil.com',
    phone: '+234 1 497 8000',
    category: 'Packaged Foods & Noodles',
    totalPurchases: 54000000,
    balanceDue: 2800000,
    rating: 4.7,
  },
  {
    id: 'supp_04',
    organizationId: DEMO_ORG_ID,
    name: 'FrieslandCampina WAMCO (Peak Milk)',
    contactPerson: 'Kemi Adebisi',
    email: 'orders@frieslandcampina.com.ng',
    phone: '+234 1 497 4100',
    category: 'Dairy Products',
    totalPurchases: 42000000,
    balanceDue: 1200000,
    rating: 4.6,
  }
];

export const demoProducts: Product[] = [
  {
    id: 'prod_01',
    organizationId: DEMO_ORG_ID,
    sku: 'FMCG-FLOUR-50KG',
    name: 'Golden Penny Premium Confectionery Flour 50kg',
    category: 'Baking & Grains',
    unitCost: 52000,
    unitPrice: 58500,
    stockQuantity: 420,
    reorderLevel: 100,
    unit: 'Bags',
    marginPercentage: 12.5,
  },
  {
    id: 'prod_02',
    organizationId: DEMO_ORG_ID,
    sku: 'FMCG-SUGAR-50KG',
    name: 'Dangote Refined White Granulated Sugar 50kg',
    category: 'Commodities',
    unitCost: 68000,
    unitPrice: 75500,
    stockQuantity: 280,
    reorderLevel: 80,
    unit: 'Bags',
    marginPercentage: 11.0,
  },
  {
    id: 'prod_03',
    organizationId: DEMO_ORG_ID,
    sku: 'FMCG-NDL-SUPER-40',
    name: 'Indomie Instant Noodles Super Pack (40 x 120g Carton)',
    category: 'Packaged Foods',
    unitCost: 11500,
    unitPrice: 13200,
    stockQuantity: 850,
    reorderLevel: 250,
    unit: 'Cartons',
    marginPercentage: 14.8,
  },
  {
    id: 'prod_04',
    organizationId: DEMO_ORG_ID,
    sku: 'FMCG-MILK-PEAK-24',
    name: 'Peak Full Cream Milk Powder (24 x 400g Tin Carton)',
    category: 'Dairy',
    unitCost: 48000,
    unitPrice: 55000,
    stockQuantity: 65,
    reorderLevel: 90,
    unit: 'Cartons',
    marginPercentage: 14.6,
  },
  {
    id: 'prod_05',
    organizationId: DEMO_ORG_ID,
    sku: 'FMCG-GINO-TOM-50',
    name: 'Gino Peppe & Onion Tomato Paste (50 x 70g Sachet Carton)',
    category: 'Condiments',
    unitCost: 8200,
    unitPrice: 9600,
    stockQuantity: 340,
    reorderLevel: 120,
    unit: 'Cartons',
    marginPercentage: 17.1,
  },
  {
    id: 'prod_06',
    organizationId: DEMO_ORG_ID,
    sku: 'FMCG-OIL-MAM-25L',
    name: 'Mamador Pure Vegetable Oil 25 Litres Keg',
    category: 'Edible Oils',
    unitCost: 41000,
    unitPrice: 46500,
    stockQuantity: 195,
    reorderLevel: 60,
    unit: 'Kegs',
    marginPercentage: 13.4,
  }
];

export const demoInvoices: Invoice[] = [
  {
    id: 'inv_01',
    organizationId: DEMO_ORG_ID,
    invoiceNumber: 'INV-2026-088',
    customerId: 'cust_01',
    customerName: 'Danladi Supermarkets Ltd',
    customerEmail: 'danladi.stores@yahoo.com',
    customerPhone: '+234 803 456 7890',
    issueDate: '2026-07-15',
    dueDate: '2026-08-14',
    lineItems: [
      { id: 'li_1', description: 'Golden Penny Flour 50kg', quantity: 60, unitPrice: 58500, total: 3510000 },
      { id: 'li_2', description: 'Dangote Refined Sugar 50kg', quantity: 40, unitPrice: 75500, total: 3020000 },
    ],
    subtotal: 6530000,
    vatRate: 7.5,
    vatAmount: 489750,
    totalAmount: 7019750,
    amountPaid: 169750,
    balanceDue: 6850000,
    status: 'OVERDUE',
    paymentTerms: 'Net 30',
    notes: '28 days overdue. AI Risk flag triggered. Action required.',
    createdAt: '2026-07-15T09:00:00.000Z',
  },
  {
    id: 'inv_02',
    organizationId: DEMO_ORG_ID,
    invoiceNumber: 'INV-2026-094',
    customerId: 'cust_02',
    customerName: 'Eze & Sons Trading Enterprises',
    customerEmail: 'jude.eze@ezesons.com.ng',
    customerPhone: '+234 802 334 5566',
    issueDate: '2026-08-01',
    dueDate: '2026-08-31',
    lineItems: [
      { id: 'li_3', description: 'Indomie Super Pack Carton', quantity: 300, unitPrice: 13200, total: 3960000 },
      { id: 'li_4', description: 'Mamador Vegetable Oil 25L', quantity: 100, unitPrice: 46500, total: 4650000 },
    ],
    subtotal: 8610000,
    vatRate: 7.5,
    vatAmount: 645750,
    totalAmount: 9255750,
    amountPaid: 55750,
    balanceDue: 9200000,
    status: 'PENDING',
    paymentTerms: 'Net 30',
    notes: 'Due today. Chief Jude confirmed bank transfer scheduling.',
    createdAt: '2026-08-01T11:00:00.000Z',
  },
  {
    id: 'inv_03',
    organizationId: DEMO_ORG_ID,
    invoiceNumber: 'INV-2026-098',
    customerId: 'cust_03',
    customerName: 'Lekki Palm Grocers & Bakery',
    customerEmail: 'purchases@lekkipalm.com',
    customerPhone: '+234 809 112 2334',
    issueDate: '2026-08-18',
    dueDate: '2026-09-02',
    lineItems: [
      { id: 'li_5', description: 'Golden Penny Flour 50kg', quantity: 80, unitPrice: 58500, total: 4680000 },
      { id: 'li_6', description: 'Peak Milk Tin Carton', quantity: 20, unitPrice: 55000, total: 1100000 },
    ],
    subtotal: 5780000,
    vatRate: 7.5,
    vatAmount: 433500,
    totalAmount: 6213500,
    amountPaid: 6213500,
    balanceDue: 0,
    status: 'PAID',
    paymentTerms: 'Net 15',
    notes: 'Paid in full via GTBank NIBSS instant transfer.',
    createdAt: '2026-08-18T14:30:00.000Z',
  },
  {
    id: 'inv_04',
    organizationId: DEMO_ORG_ID,
    invoiceNumber: 'INV-2026-101',
    customerId: 'cust_04',
    customerName: 'Kano Mega Stores & Provisioners',
    customerEmail: 'sani.garba@kanomega.ng',
    customerPhone: '+234 805 778 9900',
    issueDate: '2026-08-10',
    dueDate: '2026-09-09',
    lineItems: [
      { id: 'li_7', description: 'Dangote Sugar 50kg', quantity: 50, unitPrice: 75500, total: 3775000 },
      { id: 'li_8', description: 'Gino Tomato Paste Carton', quantity: 80, unitPrice: 9600, total: 768000 },
    ],
    subtotal: 4543000,
    vatRate: 7.5,
    vatAmount: 340725,
    totalAmount: 4883725,
    amountPaid: 783725,
    balanceDue: 4100000,
    status: 'PENDING',
    paymentTerms: 'Net 30',
    notes: 'Partial deposit paid, balance due in 9 days.',
    createdAt: '2026-08-10T16:00:00.000Z',
  },
  {
    id: 'inv_05',
    organizationId: DEMO_ORG_ID,
    invoiceNumber: 'INV-2026-079',
    customerId: 'cust_06',
    customerName: 'Garden City Retailers Consortium',
    customerEmail: 't.briggs@gardencityretail.com',
    customerPhone: '+234 803 999 1122',
    issueDate: '2026-06-25',
    dueDate: '2026-07-25',
    lineItems: [
      { id: 'li_9', description: 'Mamador Vegetable Oil 25L', quantity: 65, unitPrice: 46500, total: 3022500 },
    ],
    subtotal: 3022500,
    vatRate: 7.5,
    vatAmount: 226687.5,
    totalAmount: 3249187.5,
    amountPaid: 49187.5,
    balanceDue: 3200000,
    status: 'OVERDUE',
    paymentTerms: 'Net 30',
    notes: '37 days overdue. High risk of bad debt. Urgent collection notice sent.',
    createdAt: '2026-06-25T10:15:00.000Z',
  }
];

export const demoExpenses: Expense[] = [
  {
    id: 'exp_01',
    organizationId: DEMO_ORG_ID,
    title: 'Diesel Generator Fuel Supply (6,000 Litres for Ikeja Cold & Dry Warehouse)',
    vendor: 'TotalEnergies Marketing Nigeria Plc',
    category: 'Diesel & Power',
    amount: 7200000,
    currency: 'NGN',
    date: '2026-08-22',
    paymentMethod: 'Bank Transfer',
    receiptFileName: 'TotalEnergies_Diesel_Invoice_Aug2026.pdf',
    isTaxDeductible: true,
    isAnomalous: true,
    anomalyReason: 'Diesel cost rose by 26% compared to July due to grid outages in Ikeja Industrial zone.',
    loggedBy: 'Ngozi Ezeh',
    createdAt: '2026-08-22T15:00:00.000Z',
  },
  {
    id: 'exp_02',
    organizationId: DEMO_ORG_ID,
    title: 'Interstate Haulage Fleet (Lagos to Abuja & Kano 30-Ton Trailers)',
    vendor: 'Kobo360 Logistics Hub',
    category: 'Logistics',
    amount: 4850000,
    currency: 'NGN',
    date: '2026-08-24',
    paymentMethod: 'Bank Transfer',
    receiptFileName: 'Kobo360_Waybill_Lagos_Kano.pdf',
    isTaxDeductible: true,
    isAnomalous: false,
    loggedBy: 'Khalid Mohammed',
    createdAt: '2026-08-24T12:30:00.000Z',
  },
  {
    id: 'exp_03',
    organizationId: DEMO_ORG_ID,
    title: 'Monthly Staff Payroll (Warehouse, Drivers & Admin Staff)',
    vendor: 'Internal Payroll - Zenith Bank NXP',
    category: 'Payroll',
    amount: 8600000,
    currency: 'NGN',
    date: '2026-08-27',
    paymentMethod: 'Direct Debit',
    receiptFileName: 'Payroll_Schedule_Aug_2026.xlsx',
    isTaxDeductible: true,
    isAnomalous: false,
    loggedBy: 'Adebayo Ogunlesi',
    createdAt: '2026-08-27T17:00:00.000Z',
  },
  {
    id: 'exp_04',
    organizationId: DEMO_ORG_ID,
    title: 'Lagos State Internal Revenue Service (LIRS) WHT & Consumption Tax',
    vendor: 'Lagos State Government (LIRS)',
    category: 'Taxes & Levies',
    amount: 2150000,
    currency: 'NGN',
    date: '2026-08-15',
    paymentMethod: 'Bank Transfer',
    receiptFileName: 'LIRS_Receipt_Aug2026.pdf',
    isTaxDeductible: false,
    isAnomalous: false,
    loggedBy: 'Adebayo Ogunlesi',
    createdAt: '2026-08-15T09:00:00.000Z',
  },
  {
    id: 'exp_05',
    organizationId: DEMO_ORG_ID,
    title: 'Warehouse Forklift Fleet Overhaul & Preventive Servicing',
    vendor: 'Mantrac Nigeria (Caterpillar Dealer)',
    category: 'Maintenance',
    amount: 1450000,
    currency: 'NGN',
    date: '2026-08-18',
    paymentMethod: 'Bank Transfer',
    receiptFileName: 'Mantrac_Service_Invoice.pdf',
    isTaxDeductible: true,
    isAnomalous: false,
    loggedBy: 'Ngozi Ezeh',
    createdAt: '2026-08-18T14:00:00.000Z',
  },
  {
    id: 'exp_06',
    organizationId: DEMO_ORG_ID,
    title: 'Security Guarding & Industrial Surveillance Ikeja Complex',
    vendor: 'Halogen Security Company Ltd',
    category: 'Operations',
    amount: 850000,
    currency: 'NGN',
    date: '2026-08-05',
    paymentMethod: 'Bank Transfer',
    receiptFileName: 'Halogen_Security_Aug.pdf',
    isTaxDeductible: true,
    isAnomalous: false,
    loggedBy: 'Ngozi Ezeh',
    createdAt: '2026-08-05T11:00:00.000Z',
  }
];

export const demoTransactions: Transaction[] = [
  {
    id: 'tx_01',
    organizationId: DEMO_ORG_ID,
    type: 'RECEIVABLE_PAYMENT',
    description: 'Payment for INV-2026-098 from Lekki Palm Grocers',
    amount: 6213500,
    currency: 'NGN',
    category: 'Sales Inflow',
    date: '2026-08-28',
    referenceNumber: 'NIBSS/ZEN/20260828/99812',
    paymentMethod: 'Bank Transfer',
    relatedCustomerId: 'cust_03',
    relatedCustomerName: 'Lekki Palm Grocers & Bakery',
    relatedInvoiceId: 'inv_03',
    status: 'COMPLETED',
  },
  {
    id: 'tx_02',
    organizationId: DEMO_ORG_ID,
    type: 'EXPENSE',
    description: 'August 2026 Staff Payroll Remittance',
    amount: 8600000,
    currency: 'NGN',
    category: 'Payroll',
    date: '2026-08-27',
    referenceNumber: 'ZEN/AUTO/PAYROLL/202608',
    paymentMethod: 'Direct Debit',
    status: 'COMPLETED',
  },
  {
    id: 'tx_03',
    organizationId: DEMO_ORG_ID,
    type: 'EXPENSE',
    description: 'Haulage trip payment - 2x 30T trucks to Kano',
    amount: 4850000,
    currency: 'NGN',
    category: 'Logistics',
    date: '2026-08-24',
    referenceNumber: 'KOBO/HAUL/2026/8841',
    paymentMethod: 'Bank Transfer',
    status: 'COMPLETED',
  },
  {
    id: 'tx_04',
    organizationId: DEMO_ORG_ID,
    type: 'EXPENSE',
    description: '6,000L Diesel Delivery for Ikeja Complex',
    amount: 7200000,
    currency: 'NGN',
    category: 'Diesel & Power',
    date: '2026-08-22',
    referenceNumber: 'TOTAL/DSL/0822/01',
    paymentMethod: 'Bank Transfer',
    status: 'COMPLETED',
  },
  {
    id: 'tx_05',
    organizationId: DEMO_ORG_ID,
    type: 'INCOME',
    description: 'Direct Cash/POS Sales - Bodija Counter Store',
    amount: 2850000,
    currency: 'NGN',
    category: 'Counter Sales',
    date: '2026-08-20',
    referenceNumber: 'POS/MONIEPOINT/94821',
    paymentMethod: 'POS',
    status: 'COMPLETED',
  },
  {
    id: 'tx_06',
    organizationId: DEMO_ORG_ID,
    type: 'RECEIVABLE_PAYMENT',
    description: 'Deposit on INV-2026-101 Kano Mega Stores',
    amount: 783725,
    currency: 'NGN',
    category: 'Sales Inflow',
    date: '2026-08-10',
    referenceNumber: 'FIRSTBANK/TRF/482910',
    paymentMethod: 'Bank Transfer',
    relatedCustomerId: 'cust_04',
    relatedCustomerName: 'Kano Mega Stores & Provisioners',
    relatedInvoiceId: 'inv_04',
    status: 'COMPLETED',
  }
];

export const demoDocuments: BusinessDocument[] = [
  {
    id: 'doc_01',
    organizationId: DEMO_ORG_ID,
    title: 'Dangote Sugar Official Supply Invoice - August 2026',
    originalFileName: 'Dangote_Sugar_Invoice_AUG_2026.pdf',
    fileType: 'pdf',
    fileSize: 1420500,
    uploadDate: '2026-08-12T10:00:00.000Z',
    status: 'EXTRACTED',
    extractedData: {
      documentType: 'INVOICE',
      date: '2026-08-10',
      vendor: 'Dangote Sugar Refinery Plc',
      customer: 'Acme Distribution Nigeria',
      amount: 27200000,
      currency: 'NGN',
      invoiceNumber: 'DSR/LGS/2026/08819',
      dueDate: '2026-09-10',
      lineItems: [
        { description: 'Dangote Refined White Sugar 50kg Bag (400 Bags @ ₦68,000)', quantity: 400, amount: 27200000 }
      ],
      importantClauses: [
        'Delivery terms Ex-Factory Apapa Wharf',
        'Demurrage of ₦50,000/day applies on delayed container turnaround beyond 48 hours'
      ],
      risks: [
        'Port access corridor congestion at Apapa could delay delivery by 3-5 days',
        'Price adjustment clause if global raw sugar index shifts > 5%'
      ],
      summary: 'Bulk wholesale sugar purchase for Q3 replenishment.'
    },
    createdBy: 'Ngozi Ezeh'
  },
  {
    id: 'doc_02',
    organizationId: DEMO_ORG_ID,
    title: 'TotalEnergies Bulk Diesel Supply Waybill & Receipt',
    originalFileName: 'TotalEnergies_Diesel_Waybill_6000L.pdf',
    fileType: 'pdf',
    fileSize: 890400,
    uploadDate: '2026-08-22T16:00:00.000Z',
    status: 'EXTRACTED',
    extractedData: {
      documentType: 'WAYBILL',
      date: '2026-08-22',
      vendor: 'TotalEnergies Marketing Nigeria Plc',
      customer: 'Acme Distribution Nigeria (Ikeja Facility)',
      amount: 7200000,
      currency: 'NGN',
      invoiceNumber: 'TE-WB-88192',
      lineItems: [
        { description: 'Automotive Gas Oil (AGO / Diesel) - 6,000 Litres @ ₦1,200/L', quantity: 6000, amount: 7200000 }
      ],
      importantClauses: [
        'Certificate of quality attached: Density 0.835 kg/m3',
        'Offloading density & dipstick calibration verified by Ikeja facility manager'
      ],
      risks: [
        'Diesel unit price increased from ₦950/L to ₦1,200/L (+26.3%) in 45 days'
      ],
      summary: 'Emergency fuel purchase to sustain uninterrupted 24/7 cold room and warehouse lighting operations.'
    },
    createdBy: 'Khalid Mohammed'
  },
  {
    id: 'doc_03',
    organizationId: DEMO_ORG_ID,
    title: 'Ikeja Commercial Warehouse Lease Renewal Contract (2026-2028)',
    originalFileName: 'Warehouse_Lease_Agreement_Ikeja_2026.pdf',
    fileType: 'pdf',
    fileSize: 3450000,
    uploadDate: '2026-08-01T09:30:00.000Z',
    status: 'EXTRACTED',
    extractedData: {
      documentType: 'CONTRACT',
      date: '2026-08-01',
      vendor: 'Lagos Industrial Property Holdings Ltd',
      customer: 'Acme Distribution Nigeria',
      amount: 36000000,
      currency: 'NGN',
      dueDate: '2026-09-30',
      importantClauses: [
        'Two-year tenancy term commencing October 1, 2026',
        'Rent payable annually in advance: ₦18,000,000 per annum',
        'Service charge of 10% for external estate security and road drainage maintenance',
        'Tenant responsible for internal generator overhaul and solar inverter maintenance'
      ],
      risks: [
        'Upfront cash obligation of ₦18M due by Sept 30, 2026 will pressure liquid reserves',
        '3 months notice required for non-renewal'
      ],
      summary: 'Two-year commercial lease for 25,000 sq ft Ikeja central distribution warehouse.'
    },
    createdBy: 'Adebayo Ogunlesi'
  }
];

export const demoInsights: Insight[] = [
  {
    id: 'ins_01',
    organizationId: DEMO_ORG_ID,
    title: '₦10.05M in Overdue Receivables Threatening September Working Capital',
    category: 'Financial',
    severity: 'CRITICAL',
    section: 'URGENT',
    explanation: 'Danladi Supermarkets (₦6.85M) and Garden City Consortium (₦3.20M) are both past the 30-day payment threshold.',
    evidence: 'Invoices INV-2026-088 (28 days overdue) and INV-2026-079 (37 days overdue) account for 40.5% of total outstanding credit.',
    impact: 'If unpaid by Sept 10, cash runway will compress from 3.8 months to 2.1 months, right as the ₦18M Ikeja warehouse lease renewal falls due.',
    recommendation: 'Freeze credit limit for Garden City Consortium and initiate direct executive escalation with Alhaji Danladi with a 2% early-settlement incentive.',
    suggestedActions: [
      'Issue formal demand notice to Garden City Retailers',
      'Schedule executive call with Alhaji Danladi Usman',
      'Temporarily hold new dispatches to Danladi Supermarkets'
    ],
    resolved: false,
    generatedAt: '2026-08-31T18:00:00.000Z'
  },
  {
    id: 'ins_02',
    organizationId: DEMO_ORG_ID,
    title: 'Diesel Expenditure Spiked 26.3% - Grid Downtime Escalating Ikeja OpEx',
    category: 'Operational',
    severity: 'WARNING',
    section: 'RISKS',
    explanation: 'Generator fuel jumped from ₦950/L to ₦1,200/L, consuming 28.6% of monthly operating expenses.',
    evidence: 'Expense #exp_01 (₦7.20M) represents the largest non-payroll operational outlay in August.',
    impact: 'Operating margins for refrigerated and ambient stock reduced by 2.4 percentage points.',
    recommendation: 'Accelerate hybrid solar-inverter deployment for daytime administrative & sorting loads to cut diesel consumption by 35%.',
    suggestedActions: [
      'Obtain quotes for 30kVA Solar Micro-grid for Ikeja Warehouse',
      'Audit nighttime generator load scheduling',
      'Negotiate bulk fuel supply discount with TotalEnergies'
    ],
    resolved: false,
    generatedAt: '2026-08-31T18:00:00.000Z'
  },
  {
    id: 'ins_03',
    organizationId: DEMO_ORG_ID,
    title: 'Peak Milk Inventory Reached Critical Stockout Threshold (65 Cartons Remaining)',
    category: 'Inventory',
    severity: 'WARNING',
    section: 'RISKS',
    explanation: 'Peak Milk Tin stock is currently 65 cartons, below the safe reorder threshold of 90 cartons.',
    evidence: 'Average weekly depletion is 35 cartons; at current velocity, stockout will occur within 13 days.',
    impact: 'Estimated lost revenue of ₦3.85M from premier tier bakery clients in Lagos and Ibadan.',
    recommendation: 'Issue purchase order for 200 cartons immediately to FrieslandCampina WAMCO.',
    suggestedActions: [
      'Issue PO-2026-044 to FrieslandCampina WAMCO',
      'Confirm dispatch slot from Ikeja depot'
    ],
    resolved: false,
    generatedAt: '2026-08-31T18:00:00.000Z'
  },
  {
    id: 'ins_04',
    organizationId: DEMO_ORG_ID,
    title: 'High-Margin Tomato Paste Sachet Demand Surge in Onitsha & Ibadan',
    category: 'Growth Opportunity',
    severity: 'OPPORTUNITY',
    section: 'OPPORTUNITIES',
    explanation: 'Gino Tomato Paste delivers our highest margin (17.1%) and saw a 38% month-on-month volume expansion in South-East channels.',
    evidence: 'Bodija Mart and Eze & Sons increased repeat purchase cycle from 21 days to 9 days.',
    impact: 'Potential additional ₦6.4M monthly gross profit by expanding distribution allocation by 500 cartons.',
    recommendation: 'Bundle Gino Tomato Paste with Golden Penny Flour for tier-2 retail grocers with a 1.5% bundle incentive.',
    suggestedActions: [
      'Create FMCG Baking & Cooking retail bundle promotion',
      'Increase monthly Gino stock allocation from supplier by 40%'
    ],
    resolved: false,
    generatedAt: '2026-08-31T18:00:00.000Z'
  },
  {
    id: 'ins_05',
    organizationId: DEMO_ORG_ID,
    title: 'Early Settlement Discount Structure Can Accelerate ₦15M Cash Inflows',
    category: 'Financial',
    severity: 'OPPORTUNITY',
    section: 'OPPORTUNITIES',
    explanation: 'Top buyers like Eze & Sons and Kano Mega Stores hold substantial liquid reserves but utilize full 30-day windows.',
    evidence: 'Historical payment data indicates Eze & Sons settles within 7 days when offered a 2% prompt settlement credit.',
    impact: 'Unlocks ₦13.3M in accelerated liquid capital ahead of the September warehouse lease commitment without borrowing at 28% commercial bank rates.',
    recommendation: 'Deploy dynamic early-payment discount terms (2/10 Net 30) for top 5 credit-rated customers.',
    suggestedActions: [
      'Draft 2/10 Net 30 early settlement policy memo',
      'Send tailored early-settlement proposal to Chief Jude Eze'
    ],
    resolved: false,
    generatedAt: '2026-08-31T18:00:00.000Z'
  }
];

export const demoTasks: Task[] = [
  {
    id: 'task_01',
    organizationId: DEMO_ORG_ID,
    title: 'Executive debt recovery call with Alhaji Danladi Usman',
    description: 'Resolve overdue invoice INV-2026-088 (₦6.85M). Offer 2% discount for settlement within 5 business days or freeze subsequent orders.',
    priority: 'URGENT',
    dueDate: '2026-09-02',
    assignee: 'Efe Isiavwe',
    status: 'IN_PROGRESS',
    sourceInsight: 'ins_01',
    sourceSection: 'URGENT',
    createdAt: '2026-08-31T19:00:00.000Z'
  },
  {
    id: 'task_02',
    organizationId: DEMO_ORG_ID,
    title: 'Freeze credit and send final demand notice to Garden City Retailers',
    description: 'Invoice INV-2026-079 (₦3.2M) is 37 days overdue. Issue legal demand notice and suspend delivery routes to Port Harcourt terminal.',
    priority: 'URGENT',
    dueDate: '2026-09-03',
    assignee: 'Adebayo Ogunlesi',
    status: 'TODO',
    sourceInsight: 'ins_01',
    sourceSection: 'URGENT',
    createdAt: '2026-08-31T19:05:00.000Z'
  },
  {
    id: 'task_03',
    organizationId: DEMO_ORG_ID,
    title: 'Issue purchase order for 200 cartons Peak Milk to FrieslandCampina',
    description: 'Current inventory has dropped to 65 cartons (below safety threshold of 90). Prevent impending stockout.',
    priority: 'HIGH',
    dueDate: '2026-09-02',
    assignee: 'Ngozi Ezeh',
    status: 'TODO',
    sourceInsight: 'ins_03',
    sourceSection: 'RISKS',
    createdAt: '2026-08-31T19:10:00.000Z'
  },
  {
    id: 'task_04',
    organizationId: DEMO_ORG_ID,
    title: 'Obtain 3 formal quotes for 30kVA Solar Inverter Microgrid',
    description: 'Evaluate commercial solar providers in Ikeja to reduce monthly diesel expenditure by ₦2.5M.',
    priority: 'MEDIUM',
    dueDate: '2026-09-08',
    assignee: 'Babatunde Alabi',
    status: 'IN_PROGRESS',
    sourceInsight: 'ins_02',
    sourceSection: 'RISKS',
    createdAt: '2026-08-31T19:15:00.000Z'
  },
  {
    id: 'task_05',
    organizationId: DEMO_ORG_ID,
    title: 'Design FMCG Retail Combo bundle for South-East wholesalers',
    description: 'Bundle fast-moving Gino Tomato Paste with Golden Penny Flour to boost total basket margin.',
    priority: 'MEDIUM',
    dueDate: '2026-09-10',
    assignee: 'Khalid Mohammed',
    status: 'TODO',
    sourceInsight: 'ins_04',
    sourceSection: 'OPPORTUNITIES',
    createdAt: '2026-08-31T19:20:00.000Z'
  },
  {
    id: 'task_06',
    organizationId: DEMO_ORG_ID,
    title: 'Audit August withholding tax filings with LIRS portal',
    description: 'Reconcile remittance receipt #LIRS-AUG-8812 against Zenith Bank debit advice.',
    priority: 'LOW',
    dueDate: '2026-09-05',
    assignee: 'Adebayo Ogunlesi',
    status: 'COMPLETED',
    createdAt: '2026-08-25T10:00:00.000Z',
    completedAt: '2026-08-28T16:00:00.000Z'
  }
];

export const demoReports: ExecutiveReport[] = [
  {
    id: 'rep_01',
    organizationId: DEMO_ORG_ID,
    reportType: 'MONTHLY_MANAGEMENT',
    title: 'Executive Management Operating Review - August 2026',
    period: 'August 1 - August 31, 2026',
    generatedAt: '2026-08-31T20:00:00.000Z',
    executiveSummary: 'Acme Distribution Nigeria achieved gross sales of ₦33.1M in August across Lagos, Abuja, and Onitsha corridors. Operating profit was constrained by elevated diesel fuel expenditure (+26.3%) and delayed receivable recovery from northern distributors.',
    keyMetrics: {
      revenue: 33100000,
      expenses: 25100000,
      netProfit: 8000000,
      netMarginPercentage: 24.1,
      overdueReceivables: 10050000,
      runwayMonths: 3.8,
      cashBalance: 19450000
    },
    sections: [
      {
        heading: 'Commercial & Revenue Performance',
        content: 'Wholesale flour and packaged foods delivered steady volumes. Lekki Palm Grocers and Bodija Mart demonstrated flawless payment discipline, while Onitsha distributor Eze & Sons doubled ordering frequency for edible oils and seasonings.',
        bulletPoints: [
          'Total Gross Billing: ₦33,100,000',
          'Paid Cash Collections: ₦23,050,000',
          'Top Selling Category: Baking & Grains (₦14.2M, 42.9% of volume)'
        ]
      },
      {
        heading: 'Operating Expenses & Cost Pressures',
        content: 'OpEx totaled ₦25.1M. The primary inflationary driver was power generation (₦7.2M), driven by localized grid blackouts in the Ikeja Industrial zone. Haulage costs remained stable through our contract with Kobo360.',
        bulletPoints: [
          'Diesel & Energy: ₦7,200,000 (28.7% of OpEx)',
          'Payroll & Warehouse Labor: ₦8,600,000',
          'Logistics & Inter-state Freight: ₦4,850,000'
        ]
      },
      {
        heading: 'Working Capital & Liquidity Assessment',
        content: 'Liquid cash in Zenith Bank stands at ₦19.45M. With an upcoming ₦18.0M annual lease renewal due by September 30, aggressive collection of the ₦10.05M overdue receivables from Danladi Supermarkets and Garden City Retailers is paramount.',
        bulletPoints: [
          'Immediate Overdue Target: ₦10,050,000',
          'Upcoming 30-Day Capital Commitments: ₦23,500,000 (Lease + Dangote Sugar settlement)',
          'Current Cash Runway: 3.8 Months'
        ]
      }
    ],
    strategicPriorities: [
      'Enforce strict debt recovery on ₦10.05M overdue receivables before Sept 10',
      'Finalize Ikeja warehouse 30kVA solar hybrid installation to curb diesel overhead',
      'Roll out 2/10 Net 30 early payment discounts to accelerate cash velocity',
      'Restock Peak Milk inventory to avert bakery client stockouts'
    ],
    risksAndMitigations: [
      {
        risk: '₦18M lease cash-outflow timing coincides with delayed receivables',
        severity: 'HIGH',
        mitigation: 'Implement executive payment collection protocol and offer 2% rapid-settlement incentive.'
      },
      {
        risk: 'Persistent energy cost escalation at Ikeja central warehouse',
        severity: 'MEDIUM',
        mitigation: 'Implement nighttime equipment shutoff and procure commercial solar inverter system.'
      }
    ],
    generatedBy: 'Asivaro Executive AI Agent'
  }
];
